[package]
name = "fxsonic-dsp"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true

[lib]
name = "fxsonic_dsp"
crate-type = ["lib", "cdylib"]

[dependencies]
ladspa = { git = "https://github.com/mohiuddin200/ladspa.rs.git", branch = "master" }
fundsp = { workspace = true }
biquad = { workspace = true }
rustfft = { workspace = true }
dasp = { workspace = true }
once_cell = "1"
# libc = { workspace = true }
